export const COLORS = {
  primary: '#212025',
  onPrimary: '#FFFFFF',
  primaryContainer: '#9E9E9E',
  onPrimaryContainer: '#707070',
  secondary: '#FFFFFF',
  onSecondary: '#FAFAFA',
  tertiary: '#0824BF',
  onTertiary: '#FFFFFF',
  surface: '#F5F5F5',
  onSurface: '#A8A8A8',
  surfaceVariant: '#E0E0E0',
  onSurfaceVariant: '#1F1F1F',
  error: '#B00020',
  onError: '#FFFFFF',
  background: '#F0F0F0',
  onBackground: '#000000',
  highlight: '#FFEB3B',
  muted: '#BDBDBD',
  inverseSurface: '#D16D6D',
  inverseOnSurface: '#FFFFFF',
  inversePrimary: '#FFFFFF',
  elevation: {
    level0: 'transparent',
    level1: '#FFFFFF',
    level2: '#EBE8E8',
    level3: '#FFFFFF',
    level4: '#BDBDBD',
    level5: '#9E9E9E',
  },
};
